### PR TITLE
spectacle

### PR DESCRIPTION
**Pull request by SMOLKEYS**

### CODE REVIEW

**Comment by ThePythonGuy3** [comment]
this is so unbalanced lmao

**Comment by ThePythonGuy3** [comment]
calculate the price with the price of individual items

**Comment by ThePythonGuy3** [comment]
(amount / 15) * shop price

**Comment by SMOLKEYS** [comment]
alright but first let me feed dogs

**Comment by ThePythonGuy3** [comment]
spectacle

**Pull request merged**
